name: Spring demo GHA

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java version: '22'
          distribution: 'termurin'

      - name: Build
        run: mvn clean install

      - name: Test
        run: mvn test